# Generated by Django 5.2.13 on 2026-04-19 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('witness', 'Witness')], max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='agreements.agreement')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='identity.identityrecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agreement', 'identity', 'role'), name='unique_party_per_agreement_role')],
            },
        ),
    ]
