// Local fallback templates matching the MVP product rules doc field lists.
// When the backend ScenarioTemplate API is ready, these are replaced by the
// API response — the shape is identical.

import type { ScenarioTemplate } from "@/types/template";

export const USED_VEHICLE_SALE_TEMPLATE: ScenarioTemplate = {
  scenarioId: "used_vehicle_sale",
  version: "1.0.0",
  title: "Used vehicle sale",
  partyRoles: ["Seller", "Buyer"],
  detailSections: [
    {
      title: "Vehicle details",
      fields: [
        "vehicle_type",
        "make",
        "model",
        "year_of_manufacture",
        "registration_number",
        "vin_or_chassis",
        "current_mileage",
        "colour",
      ],
    },
    {
      title: "Ownership",
      fields: [
        "seller_is_owner_confirmed",
        "vehicle_not_under_finance_confirmed",
        "registration_documents_available",
        "roadworthy_valid",
      ],
    },
    {
      title: "Condition",
      fields: [
        "overall_condition",
        "known_mechanical_issues",
        "accident_history_known",
        "accident_history_notes",
        "included_items",
      ],
    },
    {
      title: "Price and payment",
      fields: [
        "total_price_amount",
        "payment_type",
        "payment_timing",
        "instalment_terms",
      ],
    },
    {
      title: "Handover",
      fields: ["agreement_date", "handover_date", "handover_location"],
    },
  ],
  fields: {
    vehicle_type: {
      type: "select",
      label: "Vehicle type",
      required: true,
      dataPath: "vehicle.type",
      options: [
        { value: "car", label: "Car" },
        { value: "motorbike", label: "Motorbike" },
        { value: "other", label: "Other" },
      ],
    },
    make: {
      type: "text",
      label: "Make",
      placeholder: "e.g. Toyota",
      required: true,
      dataPath: "vehicle.make",
    },
    model: {
      type: "text",
      label: "Model",
      placeholder: "e.g. Corolla",
      required: true,
      dataPath: "vehicle.model",
    },
    year_of_manufacture: {
      type: "number",
      label: "Year of manufacture",
      placeholder: "e.g. 2015",
      required: false,
      dataPath: "vehicle.year",
    },
    registration_number: {
      type: "text",
      label: "Registration number",
      placeholder: "e.g. GR-0000-20",
      required: true,
      dataPath: "vehicle.registrationNumber",
    },
    vin_or_chassis: {
      type: "text",
      label: "VIN / chassis number",
      placeholder: "Optional but recommended",
      required: false,
      dataPath: "vehicle.vin",
    },
    current_mileage: {
      type: "number",
      label: "Current mileage (km)",
      placeholder: "e.g. 120000",
      required: false,
      dataPath: "vehicle.mileage",
    },
    colour: {
      type: "text",
      label: "Colour",
      placeholder: "e.g. Silver",
      required: false,
      dataPath: "vehicle.colour",
    },
    seller_is_owner_confirmed: {
      type: "boolean",
      label: "Seller confirms they are the legal owner",
      required: true,
      dataPath: "ownership.sellerIsOwner",
    },
    vehicle_not_under_finance_confirmed: {
      type: "boolean",
      label: "Vehicle is free of any finance or loan",
      required: false,
      dataPath: "ownership.notUnderFinance",
    },
    registration_documents_available: {
      type: "boolean",
      label: "Registration documents are available",
      required: false,
      dataPath: "ownership.docsAvailable",
    },
    roadworthy_valid: {
      type: "boolean",
      label: "Roadworthy certificate is valid",
      required: false,
      dataPath: "ownership.roadworthyValid",
    },
    overall_condition: {
      type: "select",
      label: "Overall condition",
      required: false,
      dataPath: "condition.overall",
      options: [
        { value: "excellent", label: "Excellent" },
        { value: "good", label: "Good" },
        { value: "fair", label: "Fair" },
        { value: "needs_repairs", label: "Needs repairs" },
      ],
    },
    known_mechanical_issues: {
      type: "textarea",
      label: "Known mechanical issues",
      placeholder: "Describe any known issues or write 'None'",
      required: false,
      dataPath: "condition.mechanicalIssues",
    },
    accident_history_known: {
      type: "select",
      label: "Accident history",
      required: false,
      dataPath: "condition.accidentHistory",
      options: [
        { value: "no", label: "No accidents" },
        { value: "yes", label: "Yes, had accidents" },
        { value: "unknown", label: "Unknown" },
      ],
    },
    accident_history_notes: {
      type: "textarea",
      label: "Accident details",
      placeholder: "Describe the accident history",
      required: false,
      dataPath: "condition.accidentNotes",
      conditionalOn: { field: "accident_history_known", value: "yes" },
    },
    included_items: {
      type: "text",
      label: "Items included in sale",
      placeholder: "e.g. spare tyre, jack, tools",
      required: false,
      dataPath: "condition.includedItems",
    },
    total_price_amount: {
      type: "currency",
      label: "Agreed price (GHS)",
      placeholder: "0.00",
      required: true,
      dataPath: "terms.price",
    },
    payment_type: {
      type: "select",
      label: "Payment method",
      required: true,
      dataPath: "terms.paymentMethod",
      options: [
        { value: "cash", label: "Cash" },
        { value: "mobile_money", label: "Mobile money" },
        { value: "bank_transfer", label: "Bank transfer" },
        { value: "other", label: "Other" },
      ],
    },
    payment_timing: {
      type: "select",
      label: "Payment timing",
      required: true,
      dataPath: "terms.paymentTiming",
      options: [
        { value: "on_the_spot", label: "Full payment now" },
        { value: "part_now_part_later", label: "Part now, part later" },
        { value: "other", label: "Other" },
      ],
    },
    instalment_terms: {
      type: "textarea",
      label: "Instalment arrangement",
      placeholder: "Describe the payment schedule",
      required: false,
      dataPath: "terms.instalmentTerms",
      conditionalOn: { field: "payment_timing", value: "part_now_part_later" },
    },
    agreement_date: {
      type: "date",
      label: "Agreement date",
      placeholder: "YYYY-MM-DD",
      required: true,
      dataPath: "handover.agreementDate",
    },
    handover_date: {
      type: "date",
      label: "Handover date",
      placeholder: "YYYY-MM-DD (leave blank if same as above)",
      required: false,
      dataPath: "handover.handoverDate",
    },
    handover_location: {
      type: "text",
      label: "Handover location",
      placeholder: "Town or area",
      required: false,
      dataPath: "handover.location",
    },
  },
  evidenceRequirements: {
    minimumPhotoCount: 3,
    slots: [
      { id: "vehicle_photo_front", label: "Vehicle — front", fileType: "photo", required: true },
      { id: "vehicle_photo_rear", label: "Vehicle — rear", fileType: "photo", required: true },
      { id: "vehicle_odometer", label: "Dashboard / odometer", fileType: "photo", required: true },
      { id: "voice_summary", label: "Voice summary", fileType: "voice_note", required: false },
    ],
  },
};

export const RENTAL_AGREEMENT_TEMPLATE: ScenarioTemplate = {
  scenarioId: "rental_agreement",
  version: "1.0.0",
  title: "Room or house rental",
  partyRoles: ["Landlord", "Tenant"],
  detailSections: [
    {
      title: "Property details",
      fields: ["property_type", "property_address", "property_description"],
    },
    {
      title: "Tenancy terms",
      fields: [
        "rent_amount",
        "rent_period",
        "deposit_amount",
        "tenancy_start_date",
        "tenancy_end_date",
        "payment_due_day",
      ],
    },
    {
      title: "Responsibilities",
      fields: [
        "utilities_responsibility",
        "repairs_responsibility",
        "house_rules",
        "notice_period_for_termination",
      ],
    },
    {
      title: "Deposit and move-in",
      fields: ["deposit_paid", "deposit_paid_amount", "move_in_condition", "inventory_list"],
    },
  ],
  fields: {
    property_type: {
      type: "select",
      label: "Property type",
      required: true,
      dataPath: "property.type",
      options: [
        { value: "room", label: "Room" },
        { value: "apartment", label: "Apartment" },
        { value: "house", label: "House" },
        { value: "compound_room", label: "Compound room" },
      ],
    },
    property_address: {
      type: "text",
      label: "Property address",
      placeholder: "House no, area, town",
      required: true,
      dataPath: "property.address",
    },
    property_description: {
      type: "textarea",
      label: "Description",
      placeholder: "e.g. Single room with shared bath",
      required: false,
      dataPath: "property.description",
    },
    rent_amount: {
      type: "currency",
      label: "Rent amount (GHS)",
      placeholder: "0.00",
      required: true,
      dataPath: "terms.rentAmount",
    },
    rent_period: {
      type: "select",
      label: "Rent period",
      required: true,
      dataPath: "terms.rentPeriod",
      options: [
        { value: "per_month", label: "Per month" },
        { value: "per_year", label: "Per year" },
        { value: "other", label: "Other" },
      ],
    },
    deposit_amount: {
      type: "currency",
      label: "Security deposit (GHS)",
      placeholder: "0.00",
      hint: "Enter 0 if no deposit is required",
      required: true,
      dataPath: "terms.depositAmount",
    },
    tenancy_start_date: {
      type: "date",
      label: "Move-in date",
      placeholder: "YYYY-MM-DD",
      required: true,
      dataPath: "terms.startDate",
    },
    tenancy_end_date: {
      type: "date",
      label: "End date",
      placeholder: "YYYY-MM-DD (optional)",
      required: false,
      dataPath: "terms.endDate",
    },
    payment_due_day: {
      type: "text",
      label: "Payment due",
      placeholder: "e.g. 1st of each month",
      required: false,
      dataPath: "terms.paymentDueDay",
    },
    utilities_responsibility: {
      type: "textarea",
      label: "Utilities responsibility",
      placeholder: "e.g. Tenant pays ECG and water",
      required: false,
      dataPath: "responsibilities.utilities",
    },
    repairs_responsibility: {
      type: "textarea",
      label: "Repairs responsibility",
      placeholder: "e.g. Landlord handles structural repairs",
      required: false,
      dataPath: "responsibilities.repairs",
    },
    house_rules: {
      type: "textarea",
      label: "House rules",
      placeholder: "Noise, visitors, pets, etc.",
      required: false,
      dataPath: "responsibilities.houseRules",
    },
    notice_period_for_termination: {
      type: "text",
      label: "Notice period",
      placeholder: "e.g. 1 month",
      required: false,
      dataPath: "responsibilities.noticePeriod",
    },
    deposit_paid: {
      type: "boolean",
      label: "Deposit has been paid",
      required: true,
      dataPath: "moveIn.depositPaid",
    },
    deposit_paid_amount: {
      type: "currency",
      label: "Amount paid (GHS)",
      placeholder: "0.00",
      required: false,
      dataPath: "moveIn.depositPaidAmount",
      conditionalOn: { field: "deposit_paid", value: true },
    },
    move_in_condition: {
      type: "select",
      label: "Property condition at move-in",
      required: false,
      dataPath: "moveIn.condition",
      options: [
        { value: "new", label: "New / just built" },
        { value: "good", label: "Good" },
        { value: "worn", label: "Worn but usable" },
        { value: "needs_repairs", label: "Needs repairs" },
      ],
    },
    inventory_list: {
      type: "textarea",
      label: "Inventory / fixtures provided",
      placeholder: "List items included e.g. bed, fan, wardrobe",
      required: false,
      dataPath: "moveIn.inventoryList",
    },
  },
  evidenceRequirements: {
    minimumPhotoCount: 2,
    slots: [
      { id: "property_photo_entrance", label: "Property entrance", fileType: "photo", required: true },
      { id: "property_photo_interior", label: "Interior", fileType: "photo", required: true },
      { id: "property_bath", label: "Bathroom / toilet", fileType: "photo", required: false },
      { id: "voice_summary", label: "Voice summary", fileType: "voice_note", required: false },
    ],
  },
};

export const LOCAL_TEMPLATES: Record<string, ScenarioTemplate> = {
  used_vehicle_sale: USED_VEHICLE_SALE_TEMPLATE,
  rental_agreement: RENTAL_AGREEMENT_TEMPLATE,
};
