# Generated by Django 5.2.13 on 2026-04-17 12:26

import apps.agreements.domain.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('pending_consent', 'PENDING_CONSENT'), ('active', 'ACTIVE'), ('sealed', 'SEALED'), ('closed', 'CLOSED')], db_index=True, default=apps.agreements.domain.enums.AgreementStatus['DRAFT'], max_length=20)),
                ('scenario_template', models.CharField(blank=True, max_length=128)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_agreements', to='accounts.account')),
            ],
        ),
    ]
