# Generated by Django 5.2.13 on 2026-04-30 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0002_agreement_seal_hash"),
        ("parties", "0002_party_add_contact_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_consent", "Pending Consent"),
                    ("active", "Active"),
                    ("sealed", "Sealed"),
                    ("reopen_requested", "Reopen Requested"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="agreements.agreement",
                    ),
                ),
                (
                    "author_party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="parties.party",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
