# Generated by Django 5.2.13 on 2026-05-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_sprint6_annotation_and_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('seal_hash', models.CharField(max_length=64)),
                ('sealed_at', models.DateTimeField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='agreements.agreement')),
            ],
            options={
                'ordering': ['-revision_number'],
                'unique_together': {('agreement', 'revision_number')},
            },
        ),
    ]
