# Generated by Django 5.2.13 on 2026-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_agreementrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='field_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
