# Generated by Django 5.2.14 on 2026-05-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_agreement_field_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='step_index',
            field=models.IntegerField(default=0),
        ),
    ]
