# Generated by Django 5.2.13 on 2026-05-04 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultentry',
            name='evidence_item',
        ),
        migrations.RemoveField(
            model_name='vaultentry',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='export_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='is_free_retention',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='pdf_storage_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='retention_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault_entry', to='agreements.agreement'),
        ),
        migrations.AddConstraint(
            model_name='vaultentry',
            constraint=models.UniqueConstraint(fields=('agreement',), name='unique_vault_entry_per_agreement'),
        ),
    ]
