# Generated by Django 5.2.14 on 2026-05-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_vaultentry_restructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultentry',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='pdf_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
