# Generated by Django 5.2.13 on 2026-05-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0003_rename_pdf_url_to_pdf_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaultentry",
            name="pdf_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
