# Generated by Django 5.2.13 on 2026-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consent", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentrecord",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("consent", "Initial Consent"),
                    ("reopen_consent", "Reopen Consent"),
                ],
                db_index=True,
                default="consent",
                max_length=20,
            ),
        ),
    ]
