# Generated by Django 5.2.13 on 2026-04-19 09:32

import apps.identity.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=128, unique=True, validators=[apps.identity.validators.validate_identity_reference])),
                ('verification_type', models.CharField(choices=[('ghana_card', 'Ghana Card'), ('phone', 'Phone OTP')], max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='accounts.account')),
            ],
        ),
    ]
