# Generated by Django 5.2.13 on 2026-06-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_subscription_state_redesign"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invoice",
            new_name="payment_inv_account_32d0fc_idx",
            old_name="payment_inv_account_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="payment_inv_created_9f18b8_idx",
            old_name="payment_inv_created_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentevent",
            new_name="payment_eve_receive_a39f6b_idx",
            old_name="payment_eve_receive_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="payment_sub_account_a472ca_idx",
            old_name="payment_sub_account_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="payment_sub_status_f5ac8d_idx",
            old_name="payment_sub_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptioncheckout",
            new_name="payment_sub_account_9c3ead_idx",
            old_name="payment_subc_account_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptioncheckout",
            new_name="payment_sub_created_856829_idx",
            old_name="payment_subc_created_idx",
        ),
    ]
