# Generated by Django 5.2.13 on 2026-07-08 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_rename_payment_inv_account_idx_payment_inv_account_32d0fc_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptioncheckout",
            name="checkout_kind",
            field=models.CharField(
                choices=[("subscription", "Subscription"), ("recovery", "Recovery")],
                db_index=True,
                default="subscription",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptioncheckout",
            name="recovery_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recovery_checkouts",
                to="payments.subscription",
            ),
        ),
    ]
