# Generated by Django 5.2.13 on 2026-05-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_account_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountPlanProxy",
            fields=[],
            options={
                "verbose_name": "Account plan",
                "verbose_name_plural": "Account plans",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.account",),
        ),
    ]
