# Generated by Django 5.2.14 on 2026-05-14 14:44

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

_default_otp_id = lambda: f"otp_{uuid.uuid4().hex[:16]}"
_default_session_id = lambda: f"sess_{uuid.uuid4().hex[:16]}"


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.CharField(default=_default_otp_id, max_length=50, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('otp_hash', models.CharField(max_length=256)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('seal', 'Seal agreement'), ('reopen', 'Reopen agreement')], default='login', max_length=20)),
                ('agreement_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'otp_requests',
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_used'], name='otp_request_phone_19a050_idx'), models.Index(fields=['expires_at'], name='otp_request_expires_21a7df_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_pins',
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.CharField(default=_default_session_id, max_length=50, primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(max_length=256)),
                ('client_type', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web')], default='mobile', max_length=10)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('device_fingerprint', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_sessions',
                'indexes': [models.Index(fields=['user', 'is_revoked'], name='device_sess_user_id_b330dd_idx'), models.Index(fields=['expires_at'], name='device_sess_expires_a2975e_idx')],
            },
        ),
    ]
