# Generated by Django 5.2.13 on 2026-06-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_admin_mfa_code"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminmfacode",
            new_name="admin_mfa_c_user_id_d503df_idx",
            old_name="admin_mfa__user_id_b605a4_idx",
        ),
        migrations.RenameIndex(
            model_name="adminmfacode",
            new_name="admin_mfa_c_expires_536633_idx",
            old_name="admin_mfa__expires_3c3b82_idx",
        ),
    ]
